#!/bin/bash -x

declare -A Sounds


Sounds[dog]="bark"
Sounds[cow]="moo"
Sounds[bird]="tweet"
Sounds[wolf]="howl"

echo ${#Sounds[@]}
echo ${!Sounds[@]}
echo ${Sounds[@]}

for s in ${!Sounds[@]}
do
echo "sounds of " $s "is" ${Sounds[$s]};
done
